apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - files:
      - env.json
    name: application-env

images:
  - name: 428923833419.dkr.ecr.ap-northeast-2.amazonaws.com/svc/framework/papi-sample
    newTag: IMAGE_NEW_TAG
