apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::428923833419:role/eksWorknodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::428923833419:role/service-role/btiwoomCodeDeployRole 
      username: btiwoomCodeDeployRole 
      groups: 
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-03T05:17:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1013"
  uid: c38aa2a3-2f28-4a81-8710-92a2658d32d1
